# Generated by Django 5.0.6 on 2024-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adress', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(max_length=9)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
    ]
