# Generated by Django 5.0.6 on 2024-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesubjects',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
