# Generated by Django 5.0.6 on 2024-06-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurancesubjects_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceSubjects',
            new_name='InsuranceSubject',
        ),
        migrations.AlterModelOptions(
            name='insurancesubject',
            options={'verbose_name': 'Insurance Subject', 'verbose_name_plural': 'Insurance Subjects'},
        ),
    ]
